name: Dockerize
on:
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Collect docker meta
        id: docker_meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/newbiediver/rioring
          tags: |
            latest
      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v2
      - name: Login registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}